### ISSUE TITLE
Ability to included additional CSS styles in generated output file

### ISSUE THREAD

**Issue by icnocop** [undercloud/gulp-svg-inline-css#4]
Hi.

Thank you for `gulp-svg-inline-css`.

I'm using v1.3.3 and I'd like to include additional CSS styles for the image in the generated output file.

For example, the following mocha test fails (as expected):
```
    it('should include styles', function () {
        var file = {
            path: 'test.svg'
        };
        var options = {
            className: '.icon.%s',
            style: {
                backgroundRepeat: 'no-repeat'
            }
        };
        var content = '';

        content = svg.buildContent(file, options, content);

        assert.equal(".icon.test {\n  background-image: url(\'data:image/svg+xml;base64,\');\n  background-repeat: 'no-repeat';\n}\n", content);
    });
```
Output:
```
  AssertionError [ERR_ASSERTION]: '.icon.test {\n  background-image: url(\'data:image/svg+xml;base64,\');\n  background-repeat: \'no-repeat\';\n}\n' == '.icon.test {\n  background-image: url(\'data:image/svg+xml;base64,\');\n}\n'
```

As indicated in the test, I'd like the generated output to include `background-repeat: 'no-repeat';` in the CSS style.

Thank you.

**Comment by undercloud** [comment]
I think this is a bad approach, you get a lot of redundant code, if for example you have +100 icons, the solution is to use the inheritance cascade

```CSS
/* define all common styles here */
.icon {
  width: 24px;
  height: 24px;
  background-repeat: no-repeat;
  ...
}

// generated class
.icon.icon--edit {
  background-image: url('data:image/svg+xml;base64,...')
}

// add more
.icon.icon--edit {
  ...
}
```
Usage
```HTML
<span class="icon icon--edit"></span>
```
